create table Person
(
    id int generated by default as identity primary key,
    full_name varchar(100) not null unique,
    year_of_birthday int not null
);

create table Book
(
    id int generated by default as identity primary key,
    title varchar(250) not null,
    author varchar(100) not null,
    year_of_production int not null check ( year_of_production > 1550 ),
    person_id int references Person(id) on delete set null,
    taken_at timestamp
);

